-- ============================================================
-- Migration: V2__create_recipe_cuisine.sql
-- Description: Create recipe_cuisine lookup table and seed data
-- ============================================================

CREATE TABLE recipe_cuisine (
                                id                      BIGINT          PRIMARY KEY,
                                value                   VARCHAR(100)    NOT NULL UNIQUE,
                                country_localized_key   VARCHAR(255)    NOT NULL,
                                label_localized_key     VARCHAR(255)    NOT NULL,
                                flag                    VARCHAR(10)     NULL
);

-- Indexes
CREATE INDEX idx_recipe_cuisine_value ON recipe_cuisine (value);

-- ============================================================
-- Seed Data (100 cuisines)
-- ============================================================

INSERT INTO recipe_cuisine (id, value, country_localized_key, label_localized_key, flag) VALUES
                                                                                             (1,  'italian',       'cuisine.country.italy',           'cuisine.label.italian',       '🇮🇹'),
                                                                                             (2,  'japanese',      'cuisine.country.japan',           'cuisine.label.japanese',      '🇯🇵'),
                                                                                             (3,  'mexican',       'cuisine.country.mexico',          'cuisine.label.mexican',       '🇲🇽'),
                                                                                             (4,  'indian',        'cuisine.country.india',           'cuisine.label.indian',        '🇮🇳'),
                                                                                             (5,  'french',        'cuisine.country.france',          'cuisine.label.french',        '🇫🇷'),
                                                                                             (6,  'thai',          'cuisine.country.thailand',        'cuisine.label.thai',          '🇹🇭'),
                                                                                             (7,  'chinese',       'cuisine.country.china',           'cuisine.label.chinese',       '🇨🇳'),
                                                                                             (8,  'spanish',       'cuisine.country.spain',           'cuisine.label.spanish',       '🇪🇸'),
                                                                                             (9,  'lebanese',      'cuisine.country.lebanon',         'cuisine.label.lebanese',      '🇱🇧'),
                                                                                             (10, 'greek',         'cuisine.country.greece',          'cuisine.label.greek',         '🇬🇷'),
                                                                                             (11, 'pakistani',     'cuisine.country.pakistan',        'cuisine.label.pakistani',     '🇵🇰'),
                                                                                             (12, 'moroccan',      'cuisine.country.morocco',         'cuisine.label.moroccan',      '🇲🇦'),
                                                                                             (13, 'turkish',       'cuisine.country.turkey',          'cuisine.label.turkish',       '🇹🇷'),
                                                                                             (14, 'korean',        'cuisine.country.south_korea',     'cuisine.label.korean',        '🇰🇷'),
                                                                                             (15, 'vietnamese',    'cuisine.country.vietnam',         'cuisine.label.vietnamese',    '🇻🇳'),
                                                                                             (16, 'portuguese',    'cuisine.country.portugal',        'cuisine.label.portuguese',    '🇵🇹'),
                                                                                             (17, 'brazilian',     'cuisine.country.brazil',          'cuisine.label.brazilian',     '🇧🇷'),
                                                                                             (18, 'peruvian',      'cuisine.country.peru',            'cuisine.label.peruvian',      '🇵🇪'),
                                                                                             (19, 'argentinian',   'cuisine.country.argentina',       'cuisine.label.argentinian',   '🇦🇷'),
                                                                                             (20, 'egyptian',      'cuisine.country.egypt',           'cuisine.label.egyptian',      '🇪🇬'),
                                                                                             (21, 'indonesian',    'cuisine.country.indonesia',       'cuisine.label.indonesian',    '🇮🇩'),
                                                                                             (22, 'malaysian',     'cuisine.country.malaysia',        'cuisine.label.malaysian',     '🇲🇾'),
                                                                                             (23, 'singaporean',   'cuisine.country.singapore',       'cuisine.label.singaporean',   '🇸🇬'),
                                                                                             (24, 'filipino',      'cuisine.country.philippines',     'cuisine.label.filipino',      '🇵🇭'),
                                                                                             (25, 'american',      'cuisine.country.usa',             'cuisine.label.american',      '🇺🇸'),
                                                                                             (26, 'british',       'cuisine.country.united_kingdom',  'cuisine.label.british',       '🇬🇧'),
                                                                                             (27, 'german',        'cuisine.country.germany',         'cuisine.label.german',        '🇩🇪'),
                                                                                             (28, 'russian',       'cuisine.country.russia',          'cuisine.label.russian',       '🇷🇺'),
                                                                                             (29, 'ukrainian',     'cuisine.country.ukraine',         'cuisine.label.ukrainian',     '🇺🇦'),
                                                                                             (30, 'polish',        'cuisine.country.poland',          'cuisine.label.polish',        '🇵🇱'),
                                                                                             (31, 'saudi_arabian', 'cuisine.country.saudi_arabia',    'cuisine.label.saudi_arabian', '🇸🇦'),
                                                                                             (32, 'persian',       'cuisine.country.iran',            'cuisine.label.persian',       '🇮🇷'),
                                                                                             (33, 'iraqi',         'cuisine.country.iraq',            'cuisine.label.iraqi',         '🇮🇶'),
                                                                                             (34, 'syrian',        'cuisine.country.syria',           'cuisine.label.syrian',        '🇸🇾'),
                                                                                             (35, 'jordanian',     'cuisine.country.jordan',          'cuisine.label.jordanian',     '🇯🇴'),
                                                                                             (37, 'ethiopian',     'cuisine.country.ethiopia',        'cuisine.label.ethiopian',     '🇪🇹'),
                                                                                             (38, 'nigerian',      'cuisine.country.nigeria',         'cuisine.label.nigerian',      '🇳🇬'),
                                                                                             (39, 'ghanaian',      'cuisine.country.ghana',           'cuisine.label.ghanaian',      '🇬🇭'),
                                                                                             (40, 'senegalese',    'cuisine.country.senegal',         'cuisine.label.senegalese',    '🇸🇳'),
                                                                                             (41, 'kenyan',        'cuisine.country.kenya',           'cuisine.label.kenyan',        '🇰🇪'),
                                                                                             (42, 'south_african', 'cuisine.country.south_africa',    'cuisine.label.south_african', '🇿🇦'),
                                                                                             (43, 'tunisian',      'cuisine.country.tunisia',         'cuisine.label.tunisian',      '🇹🇳'),
                                                                                             (44, 'algerian',      'cuisine.country.algeria',         'cuisine.label.algerian',      '🇩🇿'),
                                                                                             (45, 'libyan',        'cuisine.country.libya',           'cuisine.label.libyan',        '🇱🇾'),
                                                                                             (46, 'colombian',     'cuisine.country.colombia',        'cuisine.label.colombian',     '🇨🇴'),
                                                                                             (47, 'venezuelan',    'cuisine.country.venezuela',       'cuisine.label.venezuelan',    '🇻🇪'),
                                                                                             (48, 'chilean',       'cuisine.country.chile',           'cuisine.label.chilean',       '🇨🇱'),
                                                                                             (49, 'bolivian',      'cuisine.country.bolivia',         'cuisine.label.bolivian',      '🇧🇴'),
                                                                                             (50, 'ecuadorian',    'cuisine.country.ecuador',         'cuisine.label.ecuadorian',    '🇪🇨'),
                                                                                             (51, 'paraguayan',    'cuisine.country.paraguay',        'cuisine.label.paraguayan',    '🇵🇾'),
                                                                                             (52, 'uruguayan',     'cuisine.country.uruguay',         'cuisine.label.uruguayan',     '🇺🇾'),
                                                                                             (53, 'canadian',      'cuisine.country.canada',          'cuisine.label.canadian',      '🇨🇦'),
                                                                                             (54, 'yucatecan',     'cuisine.country.mexico_yucatan',  'cuisine.label.yucatecan',     '🇲🇽'),
                                                                                             (55, 'cuban',         'cuisine.country.cuba',            'cuisine.label.cuban',         '🇨🇺'),
                                                                                             (56, 'jamaican',      'cuisine.country.jamaica',         'cuisine.label.jamaican',      '🇯🇲'),
                                                                                             (57, 'haitian',       'cuisine.country.haiti',           'cuisine.label.haitian',       '🇭🇹'),
                                                                                             (58, 'trinidadian',   'cuisine.country.trinidad_tobago', 'cuisine.label.trinidadian',   '🇹🇹'),
                                                                                             (59, 'puerto_rican',  'cuisine.country.puerto_rico',     'cuisine.label.puerto_rican',  '🇵🇷'),
                                                                                             (60, 'dominican',     'cuisine.country.dominican_rep',   'cuisine.label.dominican',     '🇩🇴'),
                                                                                             (61, 'australian',    'cuisine.country.australia',       'cuisine.label.australian',    '🇦🇺'),
                                                                                             (62, 'new_zealand',   'cuisine.country.new_zealand',     'cuisine.label.new_zealand',   '🇳🇿'),
                                                                                             (63, 'fijian',        'cuisine.country.fiji',            'cuisine.label.fijian',        '🇫🇯'),
                                                                                             (64, 'nepali',        'cuisine.country.nepal',           'cuisine.label.nepali',        '🇳🇵'),
                                                                                             (65, 'sri_lankan',    'cuisine.country.sri_lanka',       'cuisine.label.sri_lankan',    '🇱🇰'),
                                                                                             (66, 'bangladeshi',   'cuisine.country.bangladesh',      'cuisine.label.bangladeshi',   '🇧🇩'),
                                                                                             (67, 'burmese',       'cuisine.country.myanmar',         'cuisine.label.burmese',       '🇲🇲'),
                                                                                             (68, 'cambodian',     'cuisine.country.cambodia',        'cuisine.label.cambodian',     '🇰🇭'),
                                                                                             (69, 'laotian',       'cuisine.country.laos',            'cuisine.label.laotian',       '🇱🇦'),
                                                                                             (70, 'taiwanese',     'cuisine.country.taiwan',          'cuisine.label.taiwanese',     '🇹🇼'),
                                                                                             (71, 'mongolian',     'cuisine.country.mongolia',        'cuisine.label.mongolian',     '🇲🇳'),
                                                                                             (72, 'kazakh',        'cuisine.country.kazakhstan',      'cuisine.label.kazakh',        '🇰🇿'),
                                                                                             (73, 'uzbek',         'cuisine.country.uzbekistan',      'cuisine.label.uzbek',         '🇺🇿'),
                                                                                             (74, 'afghan',        'cuisine.country.afghanistan',     'cuisine.label.afghan',        '🇦🇫'),
                                                                                             (75, 'azerbaijani',   'cuisine.country.azerbaijan',      'cuisine.label.azerbaijani',   '🇦🇿'),
                                                                                             (76, 'georgian',      'cuisine.country.georgia',         'cuisine.label.georgian',      '🇬🇪'),
                                                                                             (77, 'armenian',      'cuisine.country.armenia',         'cuisine.label.armenian',      '🇦🇲'),
                                                                                             (78, 'swedish',       'cuisine.country.sweden',          'cuisine.label.swedish',       '🇸🇪'),
                                                                                             (79, 'norwegian',     'cuisine.country.norway',          'cuisine.label.norwegian',     '🇳🇴'),
                                                                                             (80, 'danish',        'cuisine.country.denmark',         'cuisine.label.danish',        '🇩🇰'),
                                                                                             (81, 'finnish',       'cuisine.country.finland',         'cuisine.label.finnish',       '🇫🇮'),
                                                                                             (82, 'icelandic',     'cuisine.country.iceland',         'cuisine.label.icelandic',     '🇮🇸'),
                                                                                             (83, 'dutch',         'cuisine.country.netherlands',     'cuisine.label.dutch',         '🇳🇱'),
                                                                                             (84, 'belgian',       'cuisine.country.belgium',         'cuisine.label.belgian',       '🇧🇪'),
                                                                                             (85, 'swiss',         'cuisine.country.switzerland',     'cuisine.label.swiss',         '🇨🇭'),
                                                                                             (86, 'austrian',      'cuisine.country.austria',         'cuisine.label.austrian',      '🇦🇹'),
                                                                                             (87, 'hungarian',     'cuisine.country.hungary',         'cuisine.label.hungarian',     '🇭🇺'),
                                                                                             (88, 'romanian',      'cuisine.country.romania',         'cuisine.label.romanian',      '🇷🇴'),
                                                                                             (89, 'bulgarian',     'cuisine.country.bulgaria',        'cuisine.label.bulgarian',     '🇧🇬'),
                                                                                             (90, 'serbian',       'cuisine.country.serbia',          'cuisine.label.serbian',       '🇷🇸'),
                                                                                             (91, 'croatian',      'cuisine.country.croatia',         'cuisine.label.croatian',      '🇭🇷'),
                                                                                             (92, 'guatemalan',    'cuisine.country.guatemala',       'cuisine.label.guatemalan',    '🇬🇹'),
                                                                                             (93, 'salvadoran',    'cuisine.country.el_salvador',     'cuisine.label.salvadoran',    '🇸🇻'),
                                                                                             (94, 'honduran',      'cuisine.country.honduras',        'cuisine.label.honduran',      '🇭🇳'),
                                                                                             (95, 'nicaraguan',    'cuisine.country.nicaragua',       'cuisine.label.nicaraguan',    '🇳🇮'),
                                                                                             (96, 'costa_rican',   'cuisine.country.costa_rica',      'cuisine.label.costa_rican',   '🇨🇷'),
                                                                                             (97, 'panamanian',    'cuisine.country.panama',          'cuisine.label.panamanian',    '🇵🇦'),
                                                                                             (98, 'cameroonian',   'cuisine.country.cameroon',        'cuisine.label.cameroonian',   '🇨🇲'),
                                                                                             (99, 'congolese',     'cuisine.country.dr_congo',        'cuisine.label.congolese',     '🇨🇩'),
                                                                                             (100,'tanzanian',     'cuisine.country.tanzania',        'cuisine.label.tanzanian',     '🇹🇿');