server:
  port: 9098

spring:
  application:
    name: storage-service
  profiles:
    active: firebase
  config:
    import: "optional:configserver:http://localhost:8888"

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB