server:
  port: 9098

spring:
  application:
    name: storage-service

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

firebase:
  service-account-json: ${FIREBASE_SERVICE_ACCOUNT_JSON}
  storage:
    bucket-name: ${FIREBASE_STORAGE_BUCKET}
    folder: ${FIREBASE_STORAGE_FOLDER}
