# JWT
jwt:
  secret: ${JWT_SECRET}
  access-token-expiry-ms: 300000
  refresh-token-expiry-ms: 2592000000

app:
  platforms:
    android:
      app-id: ${ANDROID_APP_ID}
      secret: ${ANDROID_APP_SECRET}

    ios:
      app-id: ${IOS_APP_ID}
      secret: ${IOS_APP_SECRET}

    web:
      app-id: ${WEB_APP_ID}
      secret: ${WEB_APP_SECRET}

    desktop:
      app-id: ${DESKTOP_APP_ID}
      secret: ${DESKTOP_APP_SECRET}

    macOS:
      app-id: ${MACOS_APP_ID}
      secret: ${MACOS_APP_SECRET}