spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 5000ms
    publisher-confirm-type: correlated
    publisher-returns: true

    template:
      mandatory: true
      retry:
        enabled: true
        initial-interval: 1s
        max-interval: 5s
        multiplier: 2.0
        max-retries: 3

    listener:
      simple:
        missing-queues-fatal: false
        retry:
          enabled: true
          initial-interval: 2000ms # Wait 2s before 1st retry
          multiplier: 2.0 # Exponential backoff (2s, 4s, 8s)
          max-retries: 3
        default-requeue-rejected: false # Crucial: Sends to DLQ after retries fail
        acknowledge-mode: auto