server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: redis,secret
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cache:
    type: redis

  cloud:
    gateway:
      server:
        webmvc:
          http-client:
            type: jdk

logging:
  level:
    io.lettuce.core: info
    org.springframework.data.redis: info